version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  commands:
    - mkdir --parents _readthedocs/html/
    - mkdir --parents _build/doctrees
    - echo $READTHEDOCS_LANGUAGE

    - |
      if [ "$READTHEDOCS_LANGUAGE" = "en" ]; then
        cp --recursive docs/build/html/* _readthedocs/html/;
        cp --recursive docs/build/doctrees/* _build/doctrees;
      fi

    - |
      if [ "$READTHEDOCS_LANGUAGE" = "ja" ]; then
        cp --recursive docs/build/html_ja/* _readthedocs/html/;
        cp --recursive docs/build/doctrees_ja/* _build/doctrees;
      fi
