[tool.poetry]
name = "pyfemtet"
version = "0.1.0"  # ignored by versioning plugin
description = "Design parameter optimization using Femtet."
authors = ["kazuma.naito <kazuma.naito@murata.com>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/pyfemtet/pyfemtet"

[tool.poetry.dependencies]
python = " >= 3.9.3, < 3.13"
numpy = "^1.26.2"
pandas = "^2.1.3"
openpyxl = "^3.1.2"
scipy = "^1.11.4"
tqdm = "^4.66.1"
optuna = "^3.4.0"
pywin32 = "^306"
femtetutils = "^1.0.0"
psutil = "^5.9.6"
dash = "^2.14.2"
plotly = "^5.18.0"
dash-bootstrap-components = "^1.5.0"
dask = "^2023.12.1"
distributed = "^2023.12.1"
colorlog = "^6.8.0"
optuna-integration = "^3.6.0"
botorch = {version = "^0.9.5", python = "<3.12"}
pip-licenses = { version = "^4.3.3", optional = true}
sphinx = { version = "==7.2.6", optional = true}
myst-parser = { version = "==2.0.0", optional = true}
sphinx-rtd-theme = { version = "==2.0.0", optional = true}
sphinx-autobuild = { version = "==2021.3.14", optional = true}
pytest = { version = "^7.4.3", optional = true}
sphinx-design = { version = "^0.5.0", optional = true}
bokeh = { version = "^3.3.3", optional = true}
pytest-dashboard = { version = "*", optional = true}
sphinx-intl = { version = "^2.2.0", optional = true}

[tool.poetry.extras]
pip-licenses = ["dev"]
sphinx = ["dev"]
myst-parser = ["dev"]
sphinx-rtd-theme = ["dev"]
sphinx-autobuild = ["dev"]
pytest = ["dev"]
sphinx-design = ["dev"]
bokeh = ["dev"]
pytest-dashboard = ["dev"]
sphinx-intl = ["dev"]

[tool.poetry.scripts]
opt-show = "pyfemtet.opt.visualization:entry_point"

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::DeprecationWarning',
]

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
