name: Upload Python Package via Poetry

# on:
#   release:
#     types: [published]
on:
  push:
    # tags:
    #   - '*'

# permissions:
#   contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Load .python-version config
      run: |
        export PYTHON_VERSION=$(cat .python-project)
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning
    - name: Poetry settings
      run: |
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry dynamic-versioning enable
        poetry config repositories.testpypi https://test.pypi.org/legacy/
    - name: Build and publish
      run: |
        poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}        
    # - name: Build and publish testpypi
    #   run: |
    #     poetry publish -r testpypi --build --username __token__ --password ${{ secrets.TESTPYPI_API_TOKEN }}
